[package]
name = "ddlog_log"
version = "0.1.0"
edition = "2018"

[features]
default = []
flatbuf = ["differential_datalog/flatbuf",]
c_api = ["differential_datalog/c_api",]

[dependencies]
differential_datalog = { path = "../../differential_datalog" }
abomonation = "0.7"
ordered-float = { version = "2.0.0", features = ["serde"] }
fnv = "1.0.2"
once_cell = "1.4.1"
libc = "0.2"
time = { version = "0.2", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
num = "0.3"
erased-serde = "0.3"
differential-dataflow = { git = "https://github.com/ddlog-dev/differential-dataflow", branch = "ddlog-1" }
timely = { git = "https://github.com/ddlog-dev/timely-dataflow", branch = "ddlog-1" }


[lib]
name = "ddlog_log"
path = "ddlog_log.rs"